apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebst06-api
  namespace: smu-team06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebst06-api
  template:
    metadata:
      labels:
        app: ebst06-api
        version: v1
    spec:
      containers:
      - name: ebst06-api
        image: smuozj/ebst06backend:v2.2
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: 32Mi
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_KEY
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: ebst06-api-service
  labels:
    app: ebst06-api
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 5000
  selector:
    app: ebst06-api
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: ebst06-api-rule
  namespace: smu-team06
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: ebst06-api-service
    port: 5000
  host: smu-team06-api
  rules:
    - path: /.*
      methods: ["GET", "POST"]
      mutators: []
      accessStrategies:
        - handler: noop
